# Generated by Django 5.2.3 on 2025-07-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do asset')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo do asset')),
                ('arquivo', models.FileField(upload_to='assets/', verbose_name='Arquivo do Asset')),
                ('versao', models.CharField(max_length=50, verbose_name='Versão')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Asset Digital',
                'verbose_name_plural': 'Assets Digitais',
            },
        ),
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cenário')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Cenário',
                'verbose_name_plural': 'Cenários',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_opcao', models.CharField(max_length=100, verbose_name='Nome da opção')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
        migrations.CreateModel(
            name='PlataformaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Plataforma de jogo')),
            ],
            options={
                'verbose_name': 'Plataforma de Jogo',
                'verbose_name_plural': 'Plataformas de Jogo',
            },
        ),
        migrations.CreateModel(
            name='TipoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de formulário de análise')),
            ],
            options={
                'verbose_name': 'Tipo de Análise',
                'verbose_name_plural': 'Tipos de Análise',
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Turno de trabalho')),
            ],
            options={
                'verbose_name': 'Turno de Trabalho',
                'verbose_name_plural': 'Turnos de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Cenario_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assetdigital', verbose_name='Asset')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cenario', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Asset do Cenário',
                'verbose_name_plural': 'Assets dos Cenários',
            },
        ),
        migrations.CreateModel(
            name='EstudioDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do estúdio')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Estúdio de Desenvolvimento',
                'verbose_name_plural': 'Estúdios de Desenvolvimento',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do jogo')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('data_lancamento', models.DateField(verbose_name='Data de lançamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiodesenvolvimento', verbose_name='Estúdio de desenvolvimento')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='EtapaDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da etapa')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de término')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Etapa de Desenvolvimento',
                'verbose_name_plural': 'Etapas de Desenvolvimento',
            },
        ),
        migrations.AddField(
            model_name='cenario',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo'),
        ),
        migrations.AddField(
            model_name='assetdigital',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo'),
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do membro')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('EstudioDesenvolvimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiodesenvolvimento', verbose_name='estudio desenvovimento')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcao', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de término')),
                ('papel', models.CharField(max_length=100, verbose_name='Papel desempenhado')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membroequipe', verbose_name='Membro da equipe')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo_ocorrencia', models.CharField(max_length=100, verbose_name='Tipo de ocorrência')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membroequipe', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Jogo_Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plataformajogo', verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Plataforma do Jogo',
                'verbose_name_plural': 'Plataformas dos Jogos',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('prioridade', models.CharField(max_length=50, verbose_name='Prioridade')),
                ('data_limite', models.DateField(verbose_name='Data limite')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etapadesenvolvimento', verbose_name='Etapa de desenvolvimento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membroequipe', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
        migrations.CreateModel(
            name='TarefaDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membroequipe', verbose_name='Membro')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Detalhamento da Tarefa',
                'verbose_name_plural': 'Detalhamentos das Tarefas',
            },
        ),
        migrations.CreateModel(
            name='AnaliseProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data_preenchimento', models.DateField(verbose_name='Data de preenchimento')),
                ('resultado', models.TextField(verbose_name='Resultado')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etapadesenvolvimento', verbose_name='Etapa de desenvolvimento')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('tipoAnalise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoanalise', verbose_name='Tipo de analise')),
            ],
            options={
                'verbose_name': 'Análise do Processo',
                'verbose_name_plural': 'Análises do Processo',
            },
        ),
        migrations.CreateModel(
            name='ComponenteProjetoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do componente')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etapadesenvolvimento', verbose_name='Etapa de desenvolvimento')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turnotrabalho', verbose_name='Turno de trabalho')),
            ],
            options={
                'verbose_name': 'Componente do Projeto',
                'verbose_name_plural': 'Componentes do Projeto',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Nome de usuário')),
                ('senha_hash', models.CharField(max_length=255, verbose_name='Senha (Hash)')),
                ('perfil', models.CharField(max_length=50, verbose_name='Perfil de acesso')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membroequipe', verbose_name='Membro associado')),
            ],
            options={
                'verbose_name': 'Usuário do Sistema',
                'verbose_name_plural': 'Usuários do Sistema',
            },
        ),
    ]
