# Generated by Django 5.2.3 on 2025-07-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenario',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='cenarios/'),
        ),
        migrations.AlterField(
            model_name='assetdigital',
            name='arquivo',
            field=models.ImageField(upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='assetdigital',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetdigital',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo'),
        ),
        migrations.AlterField(
            model_name='assetdigital',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetdigital',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetdigital',
            name='versao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cenario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cenario',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo'),
        ),
        migrations.AlterField(
            model_name='cenario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
