# Generated by Django 5.1.3 on 2025-10-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cenario_arquivo_alter_assetdigital_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do autor')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da editora')),
                ('site', models.CharField(max_length=100, verbose_name='Site da editora')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da editora')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do leitor')),
                ('email', models.CharField(max_length=100, verbose_name='Email do leitor')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF do leitor')),
            ],
            options={
                'verbose_name': 'Leitor',
                'verbose_name_plural': 'Leitores',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do livro')),
                ('preco', models.IntegerField(verbose_name='Preço do livro')),
                ('data_plub', models.DateField(verbose_name='Data de publicação do livro')),
                ('status', models.BooleanField(verbose_name='Status do livro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autor', verbose_name='Autor do livro')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.editora', verbose_name='Editora do livro')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero do livro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.RemoveField(
            model_name='alocacao',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='alocacao',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='analiseprocesso',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='analiseprocesso',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='analiseprocesso',
            name='tipoAnalise',
        ),
        migrations.RemoveField(
            model_name='assetdigital',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='cenario_asset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='cenario',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='cenario_asset',
            name='cenario',
        ),
        migrations.RemoveField(
            model_name='componenteprojetojogo',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='componenteprojetojogo',
            name='turno',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
        migrations.RemoveField(
            model_name='estudiodesenvolvimento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='EstudioDesenvolvimento',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='etapadesenvolvimento',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='jogo_plataforma',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='jogo_plataforma',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='tarefadetalhe',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='usuariosistema',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='tarefadetalhe',
            name='tarefa',
        ),
        migrations.DeleteModel(
            name='Alocacao',
        ),
        migrations.DeleteModel(
            name='AnaliseProcesso',
        ),
        migrations.DeleteModel(
            name='TipoAnalise',
        ),
        migrations.DeleteModel(
            name='AssetDigital',
        ),
        migrations.DeleteModel(
            name='Cenario',
        ),
        migrations.DeleteModel(
            name='Cenario_Asset',
        ),
        migrations.DeleteModel(
            name='ComponenteProjetoJogo',
        ),
        migrations.DeleteModel(
            name='TurnoTrabalho',
        ),
        migrations.DeleteModel(
            name='EstudioDesenvolvimento',
        ),
        migrations.DeleteModel(
            name='EtapaDesenvolvimento',
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='Jogo_Plataforma',
        ),
        migrations.DeleteModel(
            name='PlataformaJogo',
        ),
        migrations.DeleteModel(
            name='UsuarioSistema',
        ),
        migrations.DeleteModel(
            name='MembroEquipe',
        ),
        migrations.DeleteModel(
            name='Ocorrencia',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.DeleteModel(
            name='TarefaDetalhe',
        ),
    ]
