# Generated by Django 5.1.3 on 2025-10-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_autor_editora_genero_leitor_livro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
