# Generated by Django 5.2.1 on 2025-12-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_remove_autor_cidade_remove_livro_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acontecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dataAcontecimento', models.DateField(blank=True, null=True, verbose_name='Data do Acontecimento')),
                ('risco', models.CharField(blank=True, max_length=45, null=True, verbose_name='Risco')),
            ],
            options={
                'verbose_name': 'Acontecimento',
                'verbose_name_plural': 'Acontecimentos',
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resumo')),
                ('dataPublicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
        migrations.CreateModel(
            name='Desastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Desastre',
                'verbose_name_plural': 'Desastres',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=45, verbose_name='Senha')),
                ('imagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagem')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('acontecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.acontecimento', verbose_name='Acontecimento')),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.artigo', verbose_name='Artigo')),
                ('desastre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.desastre', verbose_name='Desastre')),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nivel', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nível')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desastre', verbose_name='Desastre Relacionado')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
            },
        ),
        migrations.CreateModel(
            name='TopicoArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artigo', verbose_name='Artigo')),
            ],
            options={
                'verbose_name': 'Tópico do Artigo',
                'verbose_name_plural': 'Tópicos dos Artigos',
            },
        ),
        migrations.CreateModel(
            name='TopicoDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Tópico do Desastre',
                'verbose_name_plural': 'Tópicos dos Desastres',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('horario', models.DateTimeField(auto_now_add=True, verbose_name='Horário')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario', verbose_name='Autor'),
        ),
    ]
