# Generated by Django 5.2.1 on 2025-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, default='usuario', max_length=45, null=True, verbose_name='Tipo'),
        ),
    ]
