# Generated by Django 5.2.1 on 2025-12-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_options_alter_usuario_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='aprendizado_efetivo',
            field=models.CharField(default='95%', max_length=20, verbose_name='Aprendizado Efetivo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='avaliacao_media',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3, verbose_name='Avaliação Média'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Lançamento'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='descricao_detalhada',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='desenvolvedor',
            field=models.CharField(default='A Crise G Studios', max_length=100, verbose_name='Desenvolvedor'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='download_android',
            field=models.URLField(blank=True, null=True, verbose_name='Link Download Android'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='download_ios',
            field=models.URLField(blank=True, null=True, verbose_name='Link Download iOS'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='download_windows',
            field=models.URLField(blank=True, null=True, verbose_name='Link Download Windows'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='idade_recomendada',
            field=models.CharField(default='12+ anos', max_length=50, verbose_name='Idade Recomendada'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='imagem_capa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='jogadores_ativos',
            field=models.IntegerField(default=50000, verbose_name='Jogadores Ativos'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataformas',
            field=models.CharField(default='Windows, Android, iOS', max_length=200, verbose_name='Plataformas'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tamanho',
            field=models.CharField(default='850MB (PC) / 320MB (Mobile)', max_length=50, verbose_name='Tamanho'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tempo_jogo_medio',
            field=models.CharField(default='12h', max_length=20, verbose_name='Tempo de Jogo Médio'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='versao',
            field=models.CharField(default='1.3.2', max_length=20, verbose_name='Versão'),
        ),
        migrations.CreateModel(
            name='AtualizacaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20, verbose_name='Versão')),
                ('data', models.DateField(verbose_name='Data da Atualização')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Atualização do Jogo',
                'verbose_name_plural': 'Atualizações do Jogo',
                'ordering': ['-data', '-ordem'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='fas fa-check-circle', max_length=50, verbose_name='Ícone')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Característica do Jogo',
                'verbose_name_plural': 'Características do Jogo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FAQJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.jogo')),
            ],
            options={
                'verbose_name': 'FAQ do Jogo',
                'verbose_name_plural': 'FAQs do Jogo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ImagemJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL da Imagem')),
                ('legenda', models.TextField(blank=True, null=True, verbose_name='Legenda')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Imagem do Jogo',
                'verbose_name_plural': 'Imagens do Jogo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('minimo', 'Mínimo'), ('recomendado', 'Recomendado')], default='minimo', max_length=20)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Requisito do Jogo',
                'verbose_name_plural': 'Requisitos do Jogo',
            },
        ),
    ]
