# Generated by Django 5.2.1 on 2025-12-02 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jogo_aprendizado_efetivo_jogo_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqjogo',
            options={'ordering': ['ordem', 'categoria', 'data_criacao'], 'verbose_name': 'FAQ do Jogo', 'verbose_name_plural': 'FAQs do Jogo'},
        ),
        migrations.AddField(
            model_name='faqjogo',
            name='categoria',
            field=models.CharField(choices=[('geral', 'Geral'), ('tecnico', 'Técnico'), ('jogabilidade', 'Jogabilidade'), ('pedagogico', 'Pedagógico'), ('outros', 'Outros')], default='geral', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='faqjogo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='faqjogo',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='faqjogo',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visível no Site'),
        ),
        migrations.CreateModel(
            name='PerguntaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('email', models.EmailField(max_length=254, verbose_name='Email para Resposta')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('arquivada', 'Arquivada'), ('publicada', 'Publicada como FAQ')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta_admin', models.TextField(blank=True, null=True, verbose_name='Resposta do Admin')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('admin_respondeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_respondidas', to='app.usuario', verbose_name='Admin que Respondeu')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_usuarios', to='app.jogo', verbose_name='Jogo')),
                ('publicado_como_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.faqjogo', verbose_name='Publicado como FAQ')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_enviadas', to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta do Usuário',
                'verbose_name_plural': 'Perguntas dos Usuários',
                'ordering': ['-data_envio', 'status'],
            },
        ),
    ]
